-------------POPULATE ASSOCIATION-------------	

INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(1,1);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(2,2);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(3,3);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(4,4);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(5,5);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(6,6);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(7,7);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(8,8);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(9,9);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(10,10);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(11,11);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(12,12);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(13,13);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(14,14);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(15,15);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(16,16);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(17,17);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(18,18);
--INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(19,19);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(20,20);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(21,21);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(22,22);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(23,23);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(24,24);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(25,25);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(26,26);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(27,27);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(28,28);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(29,29);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(30,30);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(31,31);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(32,32);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(33,33);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(34,34);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(35,35);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(36,36);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(37,37);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(38,38);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(39,39);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(40,40);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(41,41);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(42,42);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(43,43);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(44,44);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(45,45);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(46,46);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(47,47);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(48,48);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(49,49);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(50,50);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(51,51);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(52,52);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(53,53);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(54,54);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(55,55);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(56,56);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(57,57);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(58,58);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(59,59);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(60,60);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(61,61);
INSERT INTO user_faculty_association(user_id, faculty_id) VALUES(62,62);

------POPULATE COURSE_LOAD -------
INSERT INTO course_load(amount) VALUES(3);
INSERT INTO course_load(amount) VALUES(3);
INSERT INTO course_load(amount) VALUES(1);
INSERT INTO course_load(amount) VALUES(1);
INSERT INTO course_load(amount) VALUES(3);
INSERT INTO course_load(amount) VALUES(3);
INSERT INTO course_load(amount) VALUES(1);
INSERT INTO course_load(amount) VALUES(3);
INSERT INTO course_load(amount) VALUES(2);
INSERT INTO course_load(amount) VALUES(5);
INSERT INTO course_load(amount) VALUES(1);
INSERT INTO course_load(amount) VALUES(3);
INSERT INTO course_load(amount) VALUES(2);
INSERT INTO course_load(amount) VALUES(6);
INSERT INTO course_load(amount) VALUES(3);
INSERT INTO course_load(amount) VALUES(3);
INSERT INTO course_load(amount) VALUES(2);
INSERT INTO course_load(amount) VALUES(4);
INSERT INTO course_load(amount) VALUES(3);
INSERT INTO course_load(amount) VALUES(2);
INSERT INTO course_load(amount) VALUES(5);
INSERT INTO course_load(amount) VALUES(1);
INSERT INTO course_load(amount) VALUES(1);
INSERT INTO course_load(amount) VALUES(3);
INSERT INTO course_load(amount) VALUES(3);
INSERT INTO course_load(amount) VALUES(2);
INSERT INTO course_load(amount) VALUES(3);
INSERT INTO course_load(amount) VALUES(4);
INSERT INTO course_load(amount) VALUES(1);
INSERT INTO course_load(amount) VALUES(4);
INSERT INTO course_load(amount) VALUES(0);
INSERT INTO course_load(amount) VALUES(3);
INSERT INTO course_load(amount) VALUES(2);
INSERT INTO course_load(amount) VALUES(2);
INSERT INTO course_load(amount) VALUES(4);
INSERT INTO course_load(amount) VALUES(3);
INSERT INTO course_load(amount) VALUES(1);
INSERT INTO course_load(amount) VALUES(2);
INSERT INTO course_load(amount) VALUES(4);
INSERT INTO course_load(amount) VALUES(2);
INSERT INTO course_load(amount) VALUES(1);
INSERT INTO course_load(amount) VALUES(2);
INSERT INTO course_load(amount) VALUES(0);
